version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  tests: true

linters:
  default: standard

formatters:
  enable:
    - gci
    - gofmt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - alias
        - localmodule
      custom-order: true

    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'

    golines:
      max-len: 120
      tab-len: 4
      chain-split-dots: true
