// Package main provides a source-type plugin example.
// This plugin is compiled at runtime by devgen.
package main

import (
	"github.com/tlipoca9/devgen/genkit"
)

type MarkGen struct{}

func (m *MarkGen) Name() string { return "markgen" }

// Config returns the tool configuration for VSCode extension integration.
func (m *MarkGen) Config() genkit.ToolConfig {
	return genkit.ToolConfig{
		OutputSuffix: "_marked.go",
		Annotations: []genkit.AnnotationConfig{
			{
				Name: "mark",
				Type: "type",
				Doc:  "Mark this type for code generation",
			},
		},
	}
}

func (m *MarkGen) Run(gen *genkit.Generator, log *genkit.Logger) error {
	for _, pkg := range gen.Packages {
		var marked []string
		for _, typ := range pkg.Types {
			if genkit.HasAnnotation(typ.Doc, "markgen", "mark") {
				marked = append(marked, typ.Name)
			}
		}
		if len(marked) == 0 {
			continue
		}

		filename := genkit.OutputPath(pkg.Dir, pkg.Name+"_marked.go")
		g := gen.NewGeneratedFile(filename, pkg.GoImportPath())
		g.P("// Code generated by markgen (source plugin). DO NOT EDIT.")
		g.P()
		g.P("package ", pkg.Name)
		g.P()
		g.P("var MarkedTypes = []string{")
		for _, name := range marked {
			g.P("\t\"", name, "\",")
		}
		g.P("}")

		log.Item("markgen: generated %s", filename)
	}
	return nil
}

var Tool genkit.Tool = &MarkGen{}

func main() {}
