// Code generated by validategen. DO NOT EDIT.

package examples

import (
	"github.com/tlipoca9/devgen/cmd/validategen/examples/common"
	"testing"
)

func TestUser__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   User
		wantErr bool
	}{
		{
			name: "valid",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: false,
		},
		{
			name: "invalid_ID_required",
			input: User{
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_ID_gt",
			input: User{
				ID:              0,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_required",
			input: User{
				ID:              1,
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_min",
			input: User{
				ID:              1,
				Name:            "a",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_max",
			input: User{
				ID:              1,
				Name:            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Email_required",
			input: User{
				ID:              1,
				Name:            "aa",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Email_email",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "invalid-email",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Age_gte",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             -1,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Age_lte",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             151,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Password_required",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Password_min",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Role_oneof",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "__invalid_value__",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Website_url",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "not-a-url",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_UUID_uuid",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "not-a-uuid",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_IP_ip",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "not-an-ip",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Code_alphanum",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc-123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Code_len",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "aaaaaaa",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_OptionalAddress_required",
			input: User{
				ID:       1,
				Name:     "aa",
				Email:    "test@example.com",
				Age:      0,
				Password: "aaaaaaaa",
				Role:     "admin",
				Website:  "https://example.com",
				UUID:     "550e8400-e29b-41d4-a716-446655440000",
				IP:       "192.168.1.1",
				Code:     "abc123",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestConfig__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   Config
		wantErr bool
	}{
		{
			name: "valid",
			input: Config{
				Host:     "test",
				Port:     1,
				Tags:     make([]string, 1),
				LogLevel: "debug",
			},
			wantErr: false,
		},
		{
			name: "invalid_Host_required",
			input: Config{
				Port:     1,
				Tags:     make([]string, 1),
				LogLevel: "debug",
			},
			wantErr: true,
		},
		{
			name: "invalid_Port_required",
			input: Config{
				Host:     "test",
				Tags:     make([]string, 1),
				LogLevel: "debug",
			},
			wantErr: true,
		},
		{
			name: "invalid_Port_min",
			input: Config{
				Host:     "test",
				Port:     0,
				Tags:     make([]string, 1),
				LogLevel: "debug",
			},
			wantErr: true,
		},
		{
			name: "invalid_Port_max",
			input: Config{
				Host:     "test",
				Port:     65536,
				Tags:     make([]string, 1),
				LogLevel: "debug",
			},
			wantErr: true,
		},
		{
			name: "invalid_Tags_min",
			input: Config{
				Host:     "test",
				Port:     1,
				Tags:     make([]string, 0),
				LogLevel: "debug",
			},
			wantErr: true,
		},
		{
			name: "invalid_LogLevel_oneof",
			input: Config{
				Host:     "test",
				Port:     1,
				Tags:     make([]string, 1),
				LogLevel: "__invalid_value__",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestNetworkConfig__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   NetworkConfig
		wantErr bool
	}{
		{
			name: "valid",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "1s",
				RequestTimeout: "100ms",
			},
			wantErr: false,
		},
		{
			name: "invalid_IPv4Address_ipv4",
			input: NetworkConfig{
				IPv4Address:    "not-an-ip",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "1s",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_IPv6Address_ipv6",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "not-an-ip",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "1s",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_AnyIPAddress_ip",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "not-an-ip",
				Timeout:        "1h",
				RetryInterval:  "1s",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_Timeout_duration",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "invalid-duration",
				RetryInterval:  "1s",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_RetryInterval_duration",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "invalid-duration",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_RetryInterval_duration_min",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "1ns",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_RetryInterval_duration_max",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "1000h",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_RequestTimeout_duration_min",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "1s",
				RequestTimeout: "1ns",
			},
			wantErr: true,
		},
		{
			name: "invalid_RequestTimeout_duration_max",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "1s",
				RequestTimeout: "1000h",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestProduct__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   Product
		wantErr bool
	}{
		{
			name: "valid",
			input: Product{
				ID:       1,
				Name:     "test",
				Price:    0,
				Version:  1,
				Stock:    1,
				Discount: 99,
				Weight:   1000,
			},
			wantErr: false,
		},
		{
			name: "invalid_ID_required",
			input: Product{
				Name:     "test",
				Price:    0,
				Version:  1,
				Stock:    1,
				Discount: 99,
				Weight:   1000,
			},
			wantErr: true,
		},
		{
			name: "invalid_ID_gt",
			input: Product{
				ID:       0,
				Name:     "test",
				Price:    0,
				Version:  1,
				Stock:    1,
				Discount: 99,
				Weight:   1000,
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_required",
			input: Product{
				ID:       1,
				Price:    0,
				Version:  1,
				Stock:    1,
				Discount: 99,
				Weight:   1000,
			},
			wantErr: true,
		},
		{
			name: "invalid_Price_gte",
			input: Product{
				ID:       1,
				Name:     "test",
				Price:    -1,
				Version:  1,
				Stock:    1,
				Discount: 99,
				Weight:   1000,
			},
			wantErr: true,
		},
		{
			name: "invalid_Version_eq",
			input: Product{
				ID:       1,
				Name:     "test",
				Price:    0,
				Version:  2,
				Stock:    1,
				Discount: 99,
				Weight:   1000,
			},
			wantErr: true,
		},
		{
			name: "invalid_Stock_ne",
			input: Product{
				ID:       1,
				Name:     "test",
				Price:    0,
				Version:  1,
				Stock:    0,
				Discount: 99,
				Weight:   1000,
			},
			wantErr: true,
		},
		{
			name: "invalid_Discount_lt",
			input: Product{
				ID:       1,
				Name:     "test",
				Price:    0,
				Version:  1,
				Stock:    1,
				Discount: 100,
				Weight:   1000,
			},
			wantErr: true,
		},
		{
			name: "invalid_Weight_lte",
			input: Product{
				ID:       1,
				Name:     "test",
				Price:    0,
				Version:  1,
				Stock:    1,
				Discount: 99,
				Weight:   1001,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestStringPatterns__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   StringPatterns
		wantErr bool
	}{
		{
			name: "valid",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "abc123",
				PhoneNumber: "123456",
				Email:       "testexampletest",
				DisplayName: "validvalue",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: false,
		},
		{
			name: "invalid_FirstName_alpha",
			input: StringPatterns{
				FirstName:   "abc123",
				Username:    "abc123",
				PhoneNumber: "123456",
				Email:       "testexampletest",
				DisplayName: "validvalue",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: true,
		},
		{
			name: "invalid_Username_alphanum",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "abc-123",
				PhoneNumber: "123456",
				Email:       "testexampletest",
				DisplayName: "validvalue",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: true,
		},
		{
			name: "invalid_PhoneNumber_numeric",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "abc123",
				PhoneNumber: "12a34",
				Email:       "testexampletest",
				DisplayName: "validvalue",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: true,
		},
		{
			name: "invalid_Email_contains",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "abc123",
				PhoneNumber: "123456",
				Email:       "no_match_here",
				DisplayName: "validvalue",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: true,
		},
		{
			name: "invalid_DisplayName_excludes",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "abc123",
				PhoneNumber: "123456",
				Email:       "testexampletest",
				DisplayName: "contains_admin_here",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: true,
		},
		{
			name: "invalid_SecureURL_startswith",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "abc123",
				PhoneNumber: "123456",
				Email:       "testexampletest",
				DisplayName: "validvalue",
				SecureURL:   "wrong_prefix",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: true,
		},
		{
			name: "invalid_Domain_endswith",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "abc123",
				PhoneNumber: "123456",
				Email:       "testexampletest",
				DisplayName: "validvalue",
				SecureURL:   "https://test",
				Domain:      "wrong_suffix",
				ProductCode: "AB-1234",
			},
			wantErr: true,
		},
		{
			name: "invalid_ProductCode_regex",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "abc123",
				PhoneNumber: "123456",
				Email:       "testexampletest",
				DisplayName: "validvalue",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "!@#$%invalid",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestAllNumericTypes__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   AllNumericTypes
		wantErr bool
	}{
		{
			name: "valid",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: false,
		},
		{
			name: "invalid_Int_gt",
			input: AllNumericTypes{
				Int:     0,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Int8_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    0,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Int16_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   0,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Int32_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   0,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Int64_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   0,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Uint_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    0,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Uint8_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   0,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Uint16_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  0,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Uint32_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  0,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Uint64_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  0,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Float32_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 0,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Float64_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 0,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Byte_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    0,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Rune_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    0,
				Uintptr: 1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Uintptr_gt",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 0,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestBoolExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   BoolExample
		wantErr bool
	}{
		{
			name: "valid",
			input: BoolExample{
				IsActive:    true,
				MustBeTrue:  true,
				MustBeFalse: false,
			},
			wantErr: false,
		},
		{
			name: "invalid_IsActive_required",
			input: BoolExample{
				MustBeTrue:  true,
				MustBeFalse: false,
			},
			wantErr: true,
		},
		{
			name: "invalid_MustBeTrue_eq",
			input: BoolExample{
				IsActive:    true,
				MustBeTrue:  false,
				MustBeFalse: false,
			},
			wantErr: true,
		},
		{
			name: "invalid_MustBeFalse_ne",
			input: BoolExample{
				IsActive:    true,
				MustBeTrue:  true,
				MustBeFalse: true,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestSliceExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   SliceExample
		wantErr bool
	}{
		{
			name: "valid",
			input: SliceExample{
				Items:       make([]string, 1),
				FixedItems:  make([]int, 3),
				RequiredMap: map[string]int{"key": 0},
			},
			wantErr: false,
		},
		{
			name: "invalid_Items_required",
			input: SliceExample{
				FixedItems:  make([]int, 3),
				RequiredMap: map[string]int{"key": 0},
			},
			wantErr: true,
		},
		{
			name: "invalid_Items_min",
			input: SliceExample{
				Items:       make([]string, 0),
				FixedItems:  make([]int, 3),
				RequiredMap: map[string]int{"key": 0},
			},
			wantErr: true,
		},
		{
			name: "invalid_Items_max",
			input: SliceExample{
				Items:       make([]string, 11),
				FixedItems:  make([]int, 3),
				RequiredMap: map[string]int{"key": 0},
			},
			wantErr: true,
		},
		{
			name: "invalid_FixedItems_len",
			input: SliceExample{
				Items:       make([]string, 1),
				FixedItems:  make([]int, 4),
				RequiredMap: map[string]int{"key": 0},
			},
			wantErr: true,
		},
		{
			name: "invalid_RequiredMap_required",
			input: SliceExample{
				Items:      make([]string, 1),
				FixedItems: make([]int, 3),
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestFormatExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   FormatExample
		wantErr bool
	}{
		{
			name: "valid",
			input: FormatExample{
				JSONConfig: "{\"key\":\"value\"}",
				YAMLConfig: "key: value",
				TOMLConfig: "key = \"value\"",
				CSVData:    "a,b,c",
			},
			wantErr: false,
		},
		{
			name: "invalid_JSONConfig_format",
			input: FormatExample{
				JSONConfig: "{invalid json",
				YAMLConfig: "key: value",
				TOMLConfig: "key = \"value\"",
				CSVData:    "a,b,c",
			},
			wantErr: true,
		},
		{
			name: "invalid_YAMLConfig_format",
			input: FormatExample{
				JSONConfig: "{\"key\":\"value\"}",
				YAMLConfig: ":\n  - invalid: yaml: here",
				TOMLConfig: "key = \"value\"",
				CSVData:    "a,b,c",
			},
			wantErr: true,
		},
		{
			name: "invalid_TOMLConfig_format",
			input: FormatExample{
				JSONConfig: "{\"key\":\"value\"}",
				YAMLConfig: "key: value",
				TOMLConfig: "[invalid toml",
				CSVData:    "a,b,c",
			},
			wantErr: true,
		},
		{
			name: "invalid_CSVData_format",
			input: FormatExample{
				JSONConfig: "{\"key\":\"value\"}",
				YAMLConfig: "key: value",
				TOMLConfig: "key = \"value\"",
				CSVData:    "\"unclosed quote",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestPointerExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   PointerExample
		wantErr bool
	}{
		{
			name:    "valid",
			input:   PointerExample{},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestStringEqNeExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   StringEqNeExample
		wantErr bool
	}{
		{
			name: "valid",
			input: StringEqNeExample{
				Version: "v1",
				Status:  "test",
			},
			wantErr: false,
		},
		{
			name: "invalid_Version_eq",
			input: StringEqNeExample{
				Version: "__wrong_value__",
				Status:  "test",
			},
			wantErr: true,
		},
		{
			name: "invalid_Status_ne",
			input: StringEqNeExample{
				Version: "v1",
				Status:  "banned",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestNumericOneofExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   NumericOneofExample
		wantErr bool
	}{
		{
			name: "valid",
			input: NumericOneofExample{
				Priority:   1,
				StatusCode: 100,
			},
			wantErr: false,
		},
		{
			name: "invalid_Priority_oneof",
			input: NumericOneofExample{
				Priority:   -99999,
				StatusCode: 100,
			},
			wantErr: true,
		},
		{
			name: "invalid_StatusCode_oneof",
			input: NumericOneofExample{
				Priority:   1,
				StatusCode: -99999,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestEnumExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   EnumExample
		wantErr bool
	}{
		{
			name: "valid",
			input: EnumExample{
				Status: OrderStatusPending,
			},
			wantErr: false,
		},
		{
			name: "invalid_Status_oneof_enum",
			input: EnumExample{
				Status: OrderStatus(99999),
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestStringEnumExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   StringEnumExample
		wantErr bool
	}{
		{
			name: "valid",
			input: StringEnumExample{
				StatusStr: OrderStatusPending.String(),
			},
			wantErr: false,
		},
		{
			name: "invalid_StatusStr_oneof_enum",
			input: StringEnumExample{
				StatusStr: "__invalid__",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestCrossPackageFieldOnlyExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   CrossPackageFieldOnlyExample
		wantErr bool
	}{
		{
			name: "valid",
			input: CrossPackageFieldOnlyExample{
				Scores: make([]common.Priority, 1),
			},
			wantErr: false,
		},
		{
			name:    "invalid_Scores_required",
			input:   CrossPackageFieldOnlyExample{},
			wantErr: true,
		},
		{
			name: "invalid_Scores_min",
			input: CrossPackageFieldOnlyExample{
				Scores: make([]common.Priority, 0),
			},
			wantErr: true,
		},
		{
			name: "invalid_Scores_max",
			input: CrossPackageFieldOnlyExample{
				Scores: make([]common.Priority, 11),
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestDefaultExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   DefaultExample
		wantErr bool
	}{
		{
			name: "valid",
			input: DefaultExample{
				Host:    "test",
				Port:    1,
				Enabled: true,
				Version: 1,
				Name:    "test",
				Count:   0,
			},
			wantErr: false,
		},
		{
			name: "invalid_Name_required",
			input: DefaultExample{
				Host:    "test",
				Port:    1,
				Enabled: true,
				Version: 1,
				Count:   0,
			},
			wantErr: true,
		},
		{
			name: "invalid_Count_min",
			input: DefaultExample{
				Host:    "test",
				Port:    1,
				Enabled: true,
				Version: 1,
				Name:    "test",
				Count:   -1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Count_max",
			input: DefaultExample{
				Host:    "test",
				Port:    1,
				Enabled: true,
				Version: 1,
				Name:    "test",
				Count:   1001,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestDefaultExample_SetDefaults(t *testing.T) {
	tests := []struct {
		name   string
		input  DefaultExample
		expect DefaultExample
	}{
		{
			name:  "all_zero_values",
			input: DefaultExample{},
			expect: DefaultExample{
				Host:    "localhost",
				Port:    8080,
				Enabled: true,
				Version: 1.5,
				Name:    "unknown",
				Count:   100,
			},
		},
		{
			name: "non_zero_values_preserved",
			input: DefaultExample{
				Host:    "custom",
				Port:    999,
				Enabled: true,
				Version: 999,
				Name:    "custom",
				Count:   999,
			},
			expect: DefaultExample{
				Host:    "custom",
				Port:    999,
				Enabled: true,
				Version: 999,
				Name:    "custom",
				Count:   999,
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.input
			got.SetDefaults()
			if got.Host != tt.expect.Host {
				t.Errorf("Host = %v, want %v", got.Host, tt.expect.Host)
			}
			if got.Port != tt.expect.Port {
				t.Errorf("Port = %v, want %v", got.Port, tt.expect.Port)
			}
			if got.Enabled != tt.expect.Enabled {
				t.Errorf("Enabled = %v, want %v", got.Enabled, tt.expect.Enabled)
			}
			if got.Version != tt.expect.Version {
				t.Errorf("Version = %v, want %v", got.Version, tt.expect.Version)
			}
			if got.Name != tt.expect.Name {
				t.Errorf("Name = %v, want %v", got.Name, tt.expect.Name)
			}
			if got.Count != tt.expect.Count {
				t.Errorf("Count = %v, want %v", got.Count, tt.expect.Count)
			}
		})
	}
}
