// Code generated by enumgen. DO NOT EDIT.

package examples

import (
	"fmt"
)

// IsValid reports whether x is a valid OrderStatus.
func (x OrderStatus) IsValid() bool {
	return OrderStatusEnums.Contains(x)
}

// String returns the string representation of OrderStatus.
func (x OrderStatus) String() string {
	return OrderStatusEnums.Name(x)
}

// OrderStatusEnums is the enum helper for OrderStatus.
var OrderStatusEnums = _OrderStatusEnums{
	values: []OrderStatus{
		OrderStatusPending,
		OrderStatusPaid,
		OrderStatusShipped,
		OrderStatusDelivered,
	},
	names: map[OrderStatus]string{
		OrderStatusPending:   "Pending",
		OrderStatusPaid:      "Paid",
		OrderStatusShipped:   "Shipped",
		OrderStatusDelivered: "Delivered",
	},
	byName: map[string]OrderStatus{
		"Pending":   OrderStatusPending,
		"Paid":      OrderStatusPaid,
		"Shipped":   OrderStatusShipped,
		"Delivered": OrderStatusDelivered,
	},
}

// _OrderStatusEnums provides enum metadata and validation for OrderStatus.
type _OrderStatusEnums struct {
	values []OrderStatus
	names  map[OrderStatus]string
	byName map[string]OrderStatus
}

// List returns all valid OrderStatus values.
func (e _OrderStatusEnums) List() []OrderStatus {
	return e.values
}

// Contains reports whether v is a valid OrderStatus.
func (e _OrderStatusEnums) Contains(v OrderStatus) bool {
	_, ok := e.names[v]
	return ok
}

// Parse parses a string into OrderStatus.
func (e _OrderStatusEnums) Parse(s string) (OrderStatus, error) {
	if v, ok := e.byName[s]; ok {
		return v, nil
	}
	return 0, fmt.Errorf("invalid OrderStatus: %q", s)
}

// ContainsName reports whether name is a valid OrderStatus name.
func (e _OrderStatusEnums) ContainsName(name string) bool {
	_, ok := e.byName[name]
	return ok
}

// Name returns the string name of v.
func (e _OrderStatusEnums) Name(v OrderStatus) string {
	if name, ok := e.names[v]; ok {
		return name
	}
	return fmt.Sprintf("OrderStatus(%d)", v)
}

// Names returns all valid OrderStatus names.
func (e _OrderStatusEnums) Names() []string {
	names := make([]string, len(e.values))
	for i, v := range e.values {
		names[i] = e.names[v]
	}
	return names
}
