// Code generated by validategen. DO NOT EDIT.

package examples

import (
	"github.com/tlipoca9/devgen/cmd/validategen/examples/common"
	"testing"
)

func TestDNS1123Example__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   DNS1123Example
		wantErr bool
	}{
		{
			name: "valid",
			input: DNS1123Example{
				Hostname:    "example-name",
				ServiceName: "example-name",
				PodName:     "example-name",
			},
			wantErr: false,
		},
		{
			name: "invalid_Hostname_required",
			input: DNS1123Example{
				ServiceName: "example-name",
				PodName:     "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_Hostname_dns1123_label",
			input: DNS1123Example{
				Hostname:    "invalid-value",
				ServiceName: "example-name",
				PodName:     "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_ServiceName_required",
			input: DNS1123Example{
				Hostname: "example-name",
				PodName:  "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_ServiceName_dns1123_label",
			input: DNS1123Example{
				Hostname:    "example-name",
				ServiceName: "invalid-value",
				PodName:     "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_PodName_required",
			input: DNS1123Example{
				Hostname:    "example-name",
				ServiceName: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_PodName_dns1123_label",
			input: DNS1123Example{
				Hostname:    "example-name",
				ServiceName: "example-name",
				PodName:     "invalid-value",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestKubernetesName__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   KubernetesName
		wantErr bool
	}{
		{
			name: "valid",
			input: KubernetesName{
				Namespace:       "example-name",
				Pod:             "example-name",
				Service:         "example-name",
				StatefulSetName: "example-name",
			},
			wantErr: false,
		},
		{
			name: "invalid_Namespace_required",
			input: KubernetesName{
				Pod:             "example-name",
				Service:         "example-name",
				StatefulSetName: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_Namespace_dns1123_label",
			input: KubernetesName{
				Namespace:       "invalid-value",
				Pod:             "example-name",
				Service:         "example-name",
				StatefulSetName: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_Pod_required",
			input: KubernetesName{
				Namespace:       "example-name",
				Service:         "example-name",
				StatefulSetName: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_Pod_dns1123_label",
			input: KubernetesName{
				Namespace:       "example-name",
				Pod:             "invalid-value",
				Service:         "example-name",
				StatefulSetName: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_Service_required",
			input: KubernetesName{
				Namespace:       "example-name",
				Pod:             "example-name",
				StatefulSetName: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_Service_dns1123_label",
			input: KubernetesName{
				Namespace:       "example-name",
				Pod:             "example-name",
				Service:         "invalid-value",
				StatefulSetName: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_StatefulSetName_required",
			input: KubernetesName{
				Namespace: "example-name",
				Pod:       "example-name",
				Service:   "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_StatefulSetName_dns1123_label",
			input: KubernetesName{
				Namespace:       "example-name",
				Pod:             "example-name",
				Service:         "example-name",
				StatefulSetName: "invalid-value",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestCloudNativeService__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   CloudNativeService
		wantErr bool
	}{
		{
			name: "valid",
			input: CloudNativeService{
				DomainName:   "example-name",
				InstanceName: "example-name",
				RegistryHost: "example-name",
			},
			wantErr: false,
		},
		{
			name: "invalid_DomainName_required",
			input: CloudNativeService{
				InstanceName: "example-name",
				RegistryHost: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_DomainName_dns1123_label",
			input: CloudNativeService{
				DomainName:   "invalid-value",
				InstanceName: "example-name",
				RegistryHost: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_InstanceName_required",
			input: CloudNativeService{
				DomainName:   "example-name",
				RegistryHost: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_InstanceName_dns1123_label",
			input: CloudNativeService{
				DomainName:   "example-name",
				InstanceName: "invalid-value",
				RegistryHost: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_RegistryHost_required",
			input: CloudNativeService{
				DomainName:   "example-name",
				InstanceName: "example-name",
			},
			wantErr: true,
		},
		{
			name: "invalid_RegistryHost_dns1123_label",
			input: CloudNativeService{
				DomainName:   "example-name",
				InstanceName: "example-name",
				RegistryHost: "invalid-value",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestUser__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   User
		wantErr bool
	}{
		{
			name: "valid",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: false,
		},
		{
			name: "invalid_ID_required",
			input: User{
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_required",
			input: User{
				ID:              1,
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_min",
			input: User{
				ID:              1,
				Name:            "a",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_max",
			input: User{
				ID:              1,
				Name:            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Email_required",
			input: User{
				ID:              1,
				Name:            "aa",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Email_email",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "invalid-value",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Password_required",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Password_min",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Role_oneof",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "__invalid_value__",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Website_url",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "invalid-value",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_UUID_uuid",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "invalid-value",
				IP:              "192.168.1.1",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_IP_ip",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "invalid-value",
				Code:            "abc123",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_Code_alphanum",
			input: User{
				ID:              1,
				Name:            "aa",
				Email:           "test@example.com",
				Age:             0,
				Password:        "aaaaaaaa",
				Role:            "admin",
				Website:         "https://example.com",
				UUID:            "550e8400-e29b-41d4-a716-446655440000",
				IP:              "192.168.1.1",
				Code:            "invalid-value",
				OptionalAddress: &Address{},
			},
			wantErr: true,
		},
		{
			name: "invalid_OptionalAddress_required",
			input: User{
				ID:       1,
				Name:     "aa",
				Email:    "test@example.com",
				Age:      0,
				Password: "aaaaaaaa",
				Role:     "admin",
				Website:  "https://example.com",
				UUID:     "550e8400-e29b-41d4-a716-446655440000",
				IP:       "192.168.1.1",
				Code:     "abc123",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestConfig__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   Config
		wantErr bool
	}{
		{
			name: "valid",
			input: Config{
				Host:     "test",
				Port:     1,
				Tags:     make([]string, 1),
				LogLevel: "debug",
			},
			wantErr: false,
		},
		{
			name: "invalid_Host_required",
			input: Config{
				Port:     1,
				Tags:     make([]string, 1),
				LogLevel: "debug",
			},
			wantErr: true,
		},
		{
			name: "invalid_Port_required",
			input: Config{
				Host:     "test",
				Tags:     make([]string, 1),
				LogLevel: "debug",
			},
			wantErr: true,
		},
		{
			name: "invalid_Port_min",
			input: Config{
				Host:     "test",
				Port:     0,
				Tags:     make([]string, 1),
				LogLevel: "debug",
			},
			wantErr: true,
		},
		{
			name: "invalid_Port_max",
			input: Config{
				Host:     "test",
				Port:     65536,
				Tags:     make([]string, 1),
				LogLevel: "debug",
			},
			wantErr: true,
		},
		{
			name: "invalid_Tags_min",
			input: Config{
				Host:     "test",
				Port:     1,
				Tags:     make([]string, 0),
				LogLevel: "debug",
			},
			wantErr: true,
		},
		{
			name: "invalid_LogLevel_oneof",
			input: Config{
				Host:     "test",
				Port:     1,
				Tags:     make([]string, 1),
				LogLevel: "__invalid_value__",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestNetworkConfig__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   NetworkConfig
		wantErr bool
	}{
		{
			name: "valid",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "1s",
				RequestTimeout: "100ms",
			},
			wantErr: false,
		},
		{
			name: "invalid_IPv4Address_ipv4",
			input: NetworkConfig{
				IPv4Address:    "invalid-value",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "1s",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_IPv6Address_ipv6",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "invalid-value",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "1s",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_AnyIPAddress_ip",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "invalid-value",
				Timeout:        "1h",
				RetryInterval:  "1s",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_Timeout_duration",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "invalid-value",
				RetryInterval:  "1s",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
		{
			name: "invalid_RetryInterval_duration",
			input: NetworkConfig{
				IPv4Address:    "192.168.1.1",
				IPv6Address:    "::1",
				AnyIPAddress:   "192.168.1.1",
				Timeout:        "1h",
				RetryInterval:  "invalid-value",
				RequestTimeout: "100ms",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestProduct__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   Product
		wantErr bool
	}{
		{
			name: "valid",
			input: Product{
				ID:       1,
				Name:     "test",
				Price:    0,
				Version:  1,
				Stock:    1,
				Discount: 99,
				Weight:   1000,
			},
			wantErr: false,
		},
		{
			name: "invalid_ID_required",
			input: Product{
				Name:     "test",
				Price:    0,
				Version:  1,
				Stock:    1,
				Discount: 99,
				Weight:   1000,
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_required",
			input: Product{
				ID:       1,
				Price:    0,
				Version:  1,
				Stock:    1,
				Discount: 99,
				Weight:   1000,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestStringPatterns__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   StringPatterns
		wantErr bool
	}{
		{
			name: "valid",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "abc123",
				PhoneNumber: "123456",
				Email:       "testexampletest",
				DisplayName: "test",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: false,
		},
		{
			name: "invalid_FirstName_alpha",
			input: StringPatterns{
				FirstName:   "invalid-value",
				Username:    "abc123",
				PhoneNumber: "123456",
				Email:       "testexampletest",
				DisplayName: "test",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: true,
		},
		{
			name: "invalid_Username_alphanum",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "invalid-value",
				PhoneNumber: "123456",
				Email:       "testexampletest",
				DisplayName: "test",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: true,
		},
		{
			name: "invalid_PhoneNumber_numeric",
			input: StringPatterns{
				FirstName:   "abcdef",
				Username:    "abc123",
				PhoneNumber: "invalid-value",
				Email:       "testexampletest",
				DisplayName: "test",
				SecureURL:   "https://test",
				Domain:      "test.com",
				ProductCode: "AB-1234",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestAllNumericTypes__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   AllNumericTypes
		wantErr bool
	}{
		{
			name: "valid",
			input: AllNumericTypes{
				Int:     1,
				Int8:    1,
				Int16:   1,
				Int32:   1,
				Int64:   1,
				Uint:    1,
				Uint8:   1,
				Uint16:  1,
				Uint32:  1,
				Uint64:  1,
				Float32: 1,
				Float64: 1,
				Byte:    1,
				Rune:    1,
				Uintptr: 1,
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestBoolExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   BoolExample
		wantErr bool
	}{
		{
			name: "valid",
			input: BoolExample{
				IsActive:    true,
				MustBeTrue:  true,
				MustBeFalse: false,
			},
			wantErr: false,
		},
		{
			name: "invalid_IsActive_required",
			input: BoolExample{
				MustBeTrue:  true,
				MustBeFalse: false,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestSliceExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   SliceExample
		wantErr bool
	}{
		{
			name: "valid",
			input: SliceExample{
				Items:       make([]string, 1),
				FixedItems:  make([]int, 3),
				RequiredMap: map[string]int{"key": 0},
			},
			wantErr: false,
		},
		{
			name: "invalid_Items_required",
			input: SliceExample{
				FixedItems:  make([]int, 3),
				RequiredMap: map[string]int{"key": 0},
			},
			wantErr: true,
		},
		{
			name: "invalid_Items_min",
			input: SliceExample{
				Items:       make([]string, 0),
				FixedItems:  make([]int, 3),
				RequiredMap: map[string]int{"key": 0},
			},
			wantErr: true,
		},
		{
			name: "invalid_RequiredMap_required",
			input: SliceExample{
				Items:      make([]string, 1),
				FixedItems: make([]int, 3),
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestFormatExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   FormatExample
		wantErr bool
	}{
		{
			name: "valid",
			input: FormatExample{
				JSONConfig: "{\"key\":\"value\"}",
				YAMLConfig: "key: value",
				TOMLConfig: "key = \"value\"",
				CSVData:    "a,b,c",
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestPointerExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   PointerExample
		wantErr bool
	}{
		{
			name:    "valid",
			input:   PointerExample{},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestStringEqNeExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   StringEqNeExample
		wantErr bool
	}{
		{
			name: "valid",
			input: StringEqNeExample{
				Version: "v1",
				Status:  "test",
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestNumericOneofExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   NumericOneofExample
		wantErr bool
	}{
		{
			name: "valid",
			input: NumericOneofExample{
				Priority:   1,
				StatusCode: 100,
			},
			wantErr: false,
		},
		{
			name: "invalid_Priority_oneof",
			input: NumericOneofExample{
				Priority:   -99999,
				StatusCode: 100,
			},
			wantErr: true,
		},
		{
			name: "invalid_StatusCode_oneof",
			input: NumericOneofExample{
				Priority:   1,
				StatusCode: -99999,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestEnumExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   EnumExample
		wantErr bool
	}{
		{
			name: "valid",
			input: EnumExample{
				Status: OrderStatusPending,
			},
			wantErr: false,
		},
		{
			name: "invalid_Status_oneof_enum",
			input: EnumExample{
				Status: OrderStatus(99999),
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestStringEnumExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   StringEnumExample
		wantErr bool
	}{
		{
			name: "valid",
			input: StringEnumExample{
				StatusStr: OrderStatusPending.String(),
			},
			wantErr: false,
		},
		{
			name: "invalid_StatusStr_oneof_enum",
			input: StringEnumExample{
				StatusStr: "__invalid__",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestStringPriorityExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   StringPriorityExample
		wantErr bool
	}{
		{
			name: "valid",
			input: StringPriorityExample{
				Priority:    PriorityLow,
				PriorityStr: PriorityLow.String(),
			},
			wantErr: false,
		},
		{
			name: "invalid_Priority_oneof_enum",
			input: StringPriorityExample{
				Priority:    Priority("__invalid__"),
				PriorityStr: PriorityLow.String(),
			},
			wantErr: true,
		},
		{
			name: "invalid_PriorityStr_oneof_enum",
			input: StringPriorityExample{
				Priority:    PriorityLow,
				PriorityStr: "__invalid__",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestCrossPackageFieldOnlyExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   CrossPackageFieldOnlyExample
		wantErr bool
	}{
		{
			name: "valid",
			input: CrossPackageFieldOnlyExample{
				Scores: make([]common.Priority, 1),
			},
			wantErr: false,
		},
		{
			name:    "invalid_Scores_required",
			input:   CrossPackageFieldOnlyExample{},
			wantErr: true,
		},
		{
			name: "invalid_Scores_min",
			input: CrossPackageFieldOnlyExample{
				Scores: make([]common.Priority, 0),
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestDefaultExample__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   DefaultExample
		wantErr bool
	}{
		{
			name: "valid",
			input: DefaultExample{
				Host:    "test",
				Port:    1,
				Enabled: true,
				Version: 1,
				Name:    "test",
				Count:   0,
			},
			wantErr: false,
		},
		{
			name: "invalid_Name_required",
			input: DefaultExample{
				Host:    "test",
				Port:    1,
				Enabled: true,
				Version: 1,
				Count:   0,
			},
			wantErr: true,
		},
		{
			name: "invalid_Count_min",
			input: DefaultExample{
				Host:    "test",
				Port:    1,
				Enabled: true,
				Version: 1,
				Name:    "test",
				Count:   -1,
			},
			wantErr: true,
		},
		{
			name: "invalid_Count_max",
			input: DefaultExample{
				Host:    "test",
				Port:    1,
				Enabled: true,
				Version: 1,
				Name:    "test",
				Count:   1001,
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestDefaultExample_SetDefaults(t *testing.T) {
	tests := []struct {
		name   string
		input  DefaultExample
		expect DefaultExample
	}{
		{
			name:  "all_zero_values",
			input: DefaultExample{},
			expect: DefaultExample{
				Host:    "localhost",
				Port:    8080,
				Enabled: true,
				Version: 1.5,
				Name:    "unknown",
				Count:   100,
			},
		},
		{
			name: "non_zero_values_preserved",
			input: DefaultExample{
				Host:    "custom",
				Port:    999,
				Enabled: true,
				Version: 999,
				Name:    "custom",
				Count:   999,
			},
			expect: DefaultExample{
				Host:    "custom",
				Port:    999,
				Enabled: true,
				Version: 999,
				Name:    "custom",
				Count:   999,
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.input
			got.SetDefaults()
			if got.Host != tt.expect.Host {
				t.Errorf("Host = %v, want %v", got.Host, tt.expect.Host)
			}
			if got.Port != tt.expect.Port {
				t.Errorf("Port = %v, want %v", got.Port, tt.expect.Port)
			}
			if got.Enabled != tt.expect.Enabled {
				t.Errorf("Enabled = %v, want %v", got.Enabled, tt.expect.Enabled)
			}
			if got.Version != tt.expect.Version {
				t.Errorf("Version = %v, want %v", got.Version, tt.expect.Version)
			}
			if got.Name != tt.expect.Name {
				t.Errorf("Name = %v, want %v", got.Name, tt.expect.Name)
			}
			if got.Count != tt.expect.Count {
				t.Errorf("Count = %v, want %v", got.Count, tt.expect.Count)
			}
		})
	}
}

func TestKubernetesResource__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   KubernetesResource
		wantErr bool
	}{
		{
			name: "valid",
			input: KubernetesResource{
				CPURequest:    "100m",
				CPULimit:      "100m",
				MemoryRequest: "128Mi",
				MemoryLimit:   "128Mi",
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestPodSpec__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   PodSpec
		wantErr bool
	}{
		{
			name: "valid",
			input: PodSpec{
				Name:                   "a",
				ContainerCPURequest:    "100m",
				ContainerMemoryRequest: "128Mi",
				ContainerCPULimit:      "100m",
				ContainerMemoryLimit:   "128Mi",
			},
			wantErr: false,
		},
		{
			name: "invalid_Name_required",
			input: PodSpec{
				ContainerCPURequest:    "100m",
				ContainerMemoryRequest: "128Mi",
				ContainerCPULimit:      "100m",
				ContainerMemoryLimit:   "128Mi",
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_min",
			input: PodSpec{
				Name:                   "",
				ContainerCPURequest:    "100m",
				ContainerMemoryRequest: "128Mi",
				ContainerCPULimit:      "100m",
				ContainerMemoryLimit:   "128Mi",
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_max",
			input: PodSpec{
				Name:                   "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
				ContainerCPURequest:    "100m",
				ContainerMemoryRequest: "128Mi",
				ContainerCPULimit:      "100m",
				ContainerMemoryLimit:   "128Mi",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestKubernetesResourceSpec__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   KubernetesResourceSpec
		wantErr bool
	}{
		{
			name: "valid",
			input: KubernetesResourceSpec{
				CPURequest:    "100m",
				CPULimit:      "100m",
				MemoryRequest: "128Mi",
				MemoryLimit:   "128Mi",
			},
			wantErr: false,
		},
		{
			name: "invalid_CPURequest_required",
			input: KubernetesResourceSpec{
				CPULimit:      "100m",
				MemoryRequest: "128Mi",
				MemoryLimit:   "128Mi",
			},
			wantErr: true,
		},
		{
			name: "invalid_MemoryRequest_required",
			input: KubernetesResourceSpec{
				CPURequest:  "100m",
				CPULimit:    "100m",
				MemoryLimit: "128Mi",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}

func TestPodContainerSpec__validate(t *testing.T) {
	tests := []struct {
		name    string
		input   PodContainerSpec
		wantErr bool
	}{
		{
			name: "valid",
			input: PodContainerSpec{
				Name:          "a",
				Image:         "test",
				CPURequest:    "100m",
				MemoryRequest: "128Mi",
				CPULimit:      "100m",
				MemoryLimit:   "128Mi",
				DiskRequest:   "10Gi",
				DiskLimit:     "10Gi",
			},
			wantErr: false,
		},
		{
			name: "invalid_Name_required",
			input: PodContainerSpec{
				Image:         "test",
				CPURequest:    "100m",
				MemoryRequest: "128Mi",
				CPULimit:      "100m",
				MemoryLimit:   "128Mi",
				DiskRequest:   "10Gi",
				DiskLimit:     "10Gi",
			},
			wantErr: true,
		},
		{
			name: "invalid_Name_min",
			input: PodContainerSpec{
				Name:          "",
				Image:         "test",
				CPURequest:    "100m",
				MemoryRequest: "128Mi",
				CPULimit:      "100m",
				MemoryLimit:   "128Mi",
				DiskRequest:   "10Gi",
				DiskLimit:     "10Gi",
			},
			wantErr: true,
		},
		{
			name: "invalid_Image_required",
			input: PodContainerSpec{
				Name:          "a",
				CPURequest:    "100m",
				MemoryRequest: "128Mi",
				CPULimit:      "100m",
				MemoryLimit:   "128Mi",
				DiskRequest:   "10Gi",
				DiskLimit:     "10Gi",
			},
			wantErr: true,
		},
		{
			name: "invalid_CPURequest_required",
			input: PodContainerSpec{
				Name:          "a",
				Image:         "test",
				MemoryRequest: "128Mi",
				CPULimit:      "100m",
				MemoryLimit:   "128Mi",
				DiskRequest:   "10Gi",
				DiskLimit:     "10Gi",
			},
			wantErr: true,
		},
		{
			name: "invalid_MemoryRequest_required",
			input: PodContainerSpec{
				Name:        "a",
				Image:       "test",
				CPURequest:  "100m",
				CPULimit:    "100m",
				MemoryLimit: "128Mi",
				DiskRequest: "10Gi",
				DiskLimit:   "10Gi",
			},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			errs := tt.input._validate()
			hasErr := len(errs) > 0
			if hasErr != tt.wantErr {
				t.Errorf("_validate() errors = %v, wantErr %v", errs, tt.wantErr)
			}
		})
	}
}
