// Code generated by enumgen. DO NOT EDIT.

package common

import (
	"fmt"
)

// IsValid reports whether x is a valid Status.
func (x Status) IsValid() bool {
	return StatusEnums.Contains(x)
}

// String returns the string representation of Status.
func (x Status) String() string {
	return StatusEnums.Name(x)
}

// StatusEnums is the enum helper for Status.
var StatusEnums = _StatusEnums{
	values: []Status{
		StatusActive,
		StatusInactive,
		StatusPending,
	},
	names: map[Status]string{
		StatusActive:   "Active",
		StatusInactive: "Inactive",
		StatusPending:  "Pending",
	},
	byName: map[string]Status{
		"Active":   StatusActive,
		"Inactive": StatusInactive,
		"Pending":  StatusPending,
	},
}

// _StatusEnums provides enum metadata and validation for Status.
type _StatusEnums struct {
	values []Status
	names  map[Status]string
	byName map[string]Status
}

// List returns all valid Status values.
func (e _StatusEnums) List() []Status {
	return e.values
}

// Contains reports whether v is a valid Status.
func (e _StatusEnums) Contains(v Status) bool {
	_, ok := e.names[v]
	return ok
}

// Parse parses a string into Status.
func (e _StatusEnums) Parse(s string) (Status, error) {
	if v, ok := e.byName[s]; ok {
		return v, nil
	}
	return 0, fmt.Errorf("invalid Status: %q", s)
}

// ContainsName reports whether name is a valid Status name.
func (e _StatusEnums) ContainsName(name string) bool {
	_, ok := e.byName[name]
	return ok
}

// Name returns the string name of v.
func (e _StatusEnums) Name(v Status) string {
	if name, ok := e.names[v]; ok {
		return name
	}
	return fmt.Sprintf("Status(%d)", v)
}

// Names returns all valid Status names.
func (e _StatusEnums) Names() []string {
	names := make([]string, len(e.values))
	for i, v := range e.values {
		names[i] = e.names[v]
	}
	return names
}
