// Code generated by convertgen. DO NOT EDIT.

package convertgen

import (
	"testing"
)

func TestUserConverter_ConvertAddress(t *testing.T) {
	// Test nil input
	t.Run("nil_input", func(t *testing.T) {
		var src *Address
		dst := DefaultUserConverter.ConvertAddress(src)
		if dst != nil {
			t.Errorf("expected nil, got %v", dst)
		}
	})

	// Test basic conversion
	t.Run("basic", func(t *testing.T) {
		src := &Address{
			Street: "test_street",
			City:   "test_city",
		}
		dst := DefaultUserConverter.ConvertAddress(src)

		if dst == nil {
			t.Fatal("expected non-nil result")
		}

		if dst.Street != src.Street {
			t.Errorf("expected Street = %v, got %v", src.Street, dst.Street)
		}
		if dst.City != src.City {
			t.Errorf("expected City = %v, got %v", src.City, dst.City)
		}
	})
}

func TestUserConverter_ConvertUser(t *testing.T) {
	// Test nil input
	t.Run("nil_input", func(t *testing.T) {
		var src *User
		dst := DefaultUserConverter.ConvertUser(src)
		if dst != nil {
			t.Errorf("expected nil, got %v", dst)
		}
	})

	// Test basic conversion
	t.Run("basic", func(t *testing.T) {
		src := &User{
			ID:       42,
			FullName: "test_fullname",
			Email:    "test_email",
			Password: "test_password",
			Age:      42,
			Score:    func() *int { v := 42; return &v }(),
			Address:  &Address{},
			Tags:     []string{"test_tags"},
			Scores:   []*int{func() *int { v := 42; return &v }()},
			Meta:     map[string]string{"key": "test_meta"},
			MetaPtr:  map[string]*string{"key": func() *string { v := "test_metaptr"; return &v }()},
		}
		dst := DefaultUserConverter.ConvertUser(src)

		if dst == nil {
			t.Fatal("expected non-nil result")
		}

		if dst.ID != src.ID {
			t.Errorf("expected ID = %v, got %v", src.ID, dst.ID)
		}
		if dst.Name != src.FullName {
			t.Errorf("expected Name = %v, got %v", src.FullName, dst.Name)
		}
		if dst.Email != src.Email {
			t.Errorf("expected Email = %v, got %v", src.Email, dst.Email)
		}
		if dst.Age != src.Age {
			t.Errorf("expected Age = %v, got %v", src.Age, dst.Age)
		}
		if src.Score != nil {
			if dst.Score == nil {
				t.Error("expected Score to be non-nil")
			}
			if dst.Score == src.Score {
				t.Error("expected Score to be deep copied")
			}
		}
		if dst.Address == nil {
			t.Error("expected Address to be non-nil")
		}
		if len(dst.Tags) != len(src.Tags) {
			t.Errorf("expected Tags length %d, got %d", len(src.Tags), len(dst.Tags))
		}
		if len(dst.Scores) != len(src.Scores) {
			t.Errorf("expected Scores length %d, got %d", len(src.Scores), len(dst.Scores))
		}
		if len(dst.Meta) != len(src.Meta) {
			t.Errorf("expected Meta length %d, got %d", len(src.Meta), len(dst.Meta))
		}
		if len(dst.MetaPtr) != len(src.MetaPtr) {
			t.Errorf("expected MetaPtr length %d, got %d", len(src.MetaPtr), len(dst.MetaPtr))
		}
	})
}

func TestUserConverter_ConvertUserSlice(t *testing.T) {
	// Test nil input
	t.Run("nil_input", func(t *testing.T) {
		var src []*User
		dst := DefaultUserConverter.ConvertUserSlice(src)
		if dst != nil {
			t.Errorf("expected nil, got %v", dst)
		}
	})

	// Test basic conversion
	t.Run("basic", func(t *testing.T) {
		src := []*User{
			&User{},
		}
		dst := DefaultUserConverter.ConvertUserSlice(src)

		if len(dst) != len(src) {
			t.Errorf("expected length %d, got %d", len(src), len(dst))
		}
	})
}
