// Package main provides a pre-compiled Go plugin (.so) example.
// Build with: go build -buildmode=plugin -o goplugin.so ./examples/plugin-goplugin
package main

import (
	"github.com/tlipoca9/devgen/genkit"
)

type GoPluginGen struct{}

func (g *GoPluginGen) Name() string { return "goplugin" }

// Config returns the tool configuration for VSCode extension integration.
func (g *GoPluginGen) Config() genkit.ToolConfig {
	return genkit.ToolConfig{
		OutputSuffix: "_marked.go",
		Annotations: []genkit.AnnotationConfig{
			{
				Name: "mark",
				Type: "type",
				Doc:  "Mark this type for code generation",
			},
		},
	}
}

func (p *GoPluginGen) Run(gen *genkit.Generator, log *genkit.Logger) error {
	for _, pkg := range gen.Packages {
		var marked []string
		for _, typ := range pkg.Types {
			if genkit.HasAnnotation(typ.Doc, "goplugin", "mark") {
				marked = append(marked, typ.Name)
			}
		}
		if len(marked) == 0 {
			continue
		}

		filename := genkit.OutputPath(pkg.Dir, pkg.Name+"_marked.go")
		gf := gen.NewGeneratedFile(filename, pkg.GoImportPath())
		gf.P("// Code generated by goplugin (.so plugin). DO NOT EDIT.")
		gf.P()
		gf.P("package ", pkg.Name)
		gf.P()
		gf.P("var MarkedTypes = []string{")
		for _, name := range marked {
			gf.P("\t\"", name, "\",")
		}
		gf.P("}")

		log.Item("goplugin: generated %s", filename)
	}
	return nil
}

var Tool genkit.Tool = &GoPluginGen{}

func main() {}
